theme: jekyll-theme-slate
title: Filip Ekströms personal page

navbar-links:
  About Me: "aboutme"
  Links:
    - Instagram: "https://www.instagram.com/filipekstrm"
    - Google: "https://www.google.com"
